# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Armin Becher <becherarmin@gmail.com>
#
# SPDX-License-Identifier: Unlicense

image: "rust:latest"

variables:
    RUST_BACKTRACE: "FULL"

stages:
  - build
  - release

build_osx:
  image: joseluisq/rust-linux-darwin-builder:latest
  stage: build
  artifacts:
    paths:
      - apple-darwin.zip
  script:
    - apt-get update
    - apt-get install zip -y
    - cargo build --release --target x86_64-apple-darwin
    - zip -r apple-darwin.zip /builds/hoijui/mle_ci/target/x86_64-apple-darwin/release/

build_linux:
  stage: build
  artifacts:
    paths:
      - target/release/mle
  script:
    - cargo build --verbose --release

test_latest:
    stage: build
    script:
      - cargo test --all --verbose

test_nightly:
    stage: build
    image: rustlang/rust:nightly
    script:
      - cargo test --all --verbose
    allow_failure: true

release_github_artifact:
  stage: release
  image: golang:latest
  script:
    - go get github.com/aktau/github-release
    - github-release release --user hoijui --repo mle --tag $CI_COMMIT_TAG
    - github-release upload --user hoijui --repo mle --tag $CI_COMMIT_TAG --name "mle-x86_64-linux" --file target/release/mle
    - github-release upload --user hoijui --repo mle --tag $CI_COMMIT_TAG --name "mle-x86_64-apple-darwin" --file apple-darwin.zip
  only:
    - tags

release_docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t hoijui/mle .
    - version="${CI_COMMIT_TAG:1}"
    - docker tag hoijui/mle hoijui/mle:$version
    - docker push hoijui/mle
  only:
    - tags
