# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Armin Becher <becherarmin@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "mle"
version = "0.14.4-alpha.0"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
edition = "2018"
description = "The markup link extractor (mle) extracts links from markup files (Markdown and HTML)."
keywords = ["link-extractor", "markup", "html", "markdown"]
readme = "README.md"
license = "AGPL-3.0-or-later"
repository = "https://github.com/hoijui/mle"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-open-issues = { repository = "hoijui/mle" }
is-it-maintained-issue-resolution = { repository = "hoijui/mle" }

[dependencies]
async-std = "1.9.0"
clap = { version = "3.2", features = ["cargo", "wrap_help"] }
clap_derive = "3.2"
colored = "2"
const_format = "0.2"
# email_address = "0.2"
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4.11"
#pulldown-cmark = {git = "https://github.com/lo48576/pulldown-cmark", branch="feature/heading-attrs"}
pulldown-cmark = "0.9.1"
regex = "1"
relative-path = "1.7"
reqwest = { version = "0.11.3", features = ["native-tls-vendored"] }
simplelog = "0.10"
tokio = { version = "1.5", features = ["rt-multi-thread", "macros", "time"] }
url = "2.2.1"
walkdir = "2.3.1"
wildmatch = "2.1.0"

[dev-dependencies]
criterion = "0.3.4"
ntest = "0.7.3"

[[bench]]
name = "benchmarks"
harness = false
