[package]
name = "mlc"
version = "0.14.4-alpha.0"
authors = ["Armin Becher <becherarmin@gmail.com>"]
edition = "2018"
description = "The markup link checker (mlc) checks for broken links in markup files."
keywords = [ "link-checker", "broken", "markup", "html", "markdown"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/becheran/mlc"

[badges]
maintenance = { status = "actively-developed" }
is-it-maintained-open-issues = { repository = "becheran/mlc" }
is-it-maintained-issue-resolution = { repository = "becheran/mlc" }

[dependencies]
clap = "2.33.3"
log = "0.4.11"
simplelog = "0.10"
walkdir = "2.3.1"
regex = "1"
lazy_static = "1.4.0"
url = "2.2.1"
colored = "2"
async-std = "1.9.0"
reqwest = {version="0.11.3", features = ["native-tls-vendored"] }
tokio = {version="1.5", features = ["rt-multi-thread", "macros", "time"] }
futures = "0.3"
wildmatch = "2.1.0"
pulldown-cmark = "0.8.0"

[dev-dependencies]
ntest = "0.7.3"
criterion = "0.3.4"

[[bench]]
name = "benchmarks"
harness = false
