# SPDX-FileCopyrightText: 2022 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-FileCopyrightText: 2020 Armin Becher <becherarmin@gmail.com>
#
# SPDX-License-Identifier: Unlicense

pre-release-replacements = [
  {file="README.md", search="releases/download/v[0-9\\.-]+", replace="releases/download/v{{version}}"},
  {file="README.md", search="mle@v[0-9\\.-]+", replace="mle@v{{version}}"},
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate"},
  {file="GithubAction-Dockerfile", search="FROM becheran/mle:[0-9\\.-]+", replace="FROM becheran/mle:{{version}}"},
]
